Criminal-Web-Station/Controllers/ChatController.cs
namespace Criminal_Web_Station.Controllers
{
    using Criminal_Web_Station.Data.Entities;
    using Criminal_Web_Station.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    public class ChatController : Controller
    {
        private readonly UserManager<Account> userManager;

        public ChatController(UserManager<Account> userManager)
        {
            this.userManager = userManager;
        }
        [Authorize]
        [HttpGet]
        public IActionResult Messages()
        {
            var userId = this.userManager.GetUserAsync(this.User).Result.Id;
            var userViewModel = new UserChatInputModel
            {
                Id = userId
            };

            return View(userViewModel);
        }
    }
}

Criminal-Web-Station/Controllers/ItemController.cs
namespace Criminal_Web_Station.Controllers
{
    using Criminal_Web_Station.Data.Entities;
    using Criminal_Web_Station.Models.Item;
    using Criminal_Web_Station.Services.Interfaces;
    using Criminal_Web_Station.Services.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    public class ItemController : Controller
    {
        private readonly UserManager<Account> userManager;
        private readonly IItemService itemService;
        private readonly IMarketService marketService;
        public ItemController(
            UserManager<Account> userManager,
            IItemService itemService,
            IMarketService marketService)
        {
            this.userManager = userManager;
            this.itemService = itemService;
            this.marketService = marketService;
        }
        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            return View(new ItemInputFormModel
            {
                Categories = this.itemService.AllCategories()
            });
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(ItemInputFormModel item)
        {
            if (!this.ModelState.IsValid)
            {
                item.Categories = this.itemService.AllCategories();
                return View(item);
            }

            var accountId = this.userManager.GetUserAsync(this.User).Result.Id;

            await itemService.CreateAsync(item, accountId);
            this.TempData.Add(WebConstats.Message, WebConstats.ItemAddMessage);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Authorize]
        public IActionResult Edit(string id)
        {
            var itemEditModel = this.itemService.GetItemByIdGeneric<ItemInputFormModel>(id);
            itemEditModel.Categories = this.itemService.AllCategories();

            return View(itemEditModel);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(ItemInputFormModel itemInput, string id)
        {
            if (!this.ModelState.IsValid)
            {
                itemInput.Categories = this.itemService.AllCategories();
                return View(itemInput);
            }

            this.itemService.EditItem(itemInput, id);
            this.TempData[WebConstats.Message] = WebConstats.ItemHasBeenEdited;

            return RedirectToAction("CurrentAdds", "UserAdds");
        }

        [Authorize]
        public async Task<IActionResult> Delete(string id)
        {
            await this.itemService.DeleteItemAsync(id);
            this.TempData[WebConstats.Warning] = WebConstats.ItemHasBeenDeleted;

            return RedirectToAction("CurrentAdds", "UserAdds");
        }

        [HttpGet]
        [Authorize]
        public IActionResult Details(string id)
        {
            var viewItemModel = this.itemService.GetItemByIdGeneric<ItemInputFormModel>(id);

            var username = this.userManager.FindByIdAsync(viewItemModel.AccountId).Result.UserName;
            viewItemModel.Username = username;

            return View(viewItemModel);
        }
        [HttpGet]
        public IActionResult All(AllItemsServiceModel itemModel)
        {
            var allItems = this.marketService
                .AllItems(
                itemModel.Filter,
                itemModel.SearchTerm,
                itemModel.Sorting,
                itemModel.CurrentPage,
                AllItemsServiceModel.ItemsPerPage);

            return View(allItems);
        }
    }
}

Criminal-Web-Station/Views/Shared/_Layout.cshtml
@inject UserManager<Account> userManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Criminal Station</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/shoppingCart.css" />
    <link rel="stylesheet" href="~/css/creditCard.css" />
    <link rel="icon" href="https://img.icons8.com/office/16/000000/crime.png">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Criminal Station</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="All">Market</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chat" asp-action="Messages">Chatroom</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserAdds" asp-action="CurrentAdds">My Adds</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Create">Add Item</a>
                            </li>
                            if (User.IsInRole(AdminConstants.AdministratorRoleName))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Items" asp-action="Statistics">Statistics</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Users" asp-action="All">Users</a>
                                </li>
                            }
                        }
                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="mr-3" asp-area="" asp-controller="ShoppingCart" asp-action="Index">
                            <img class="img-cart" src="~/shoppingCart.png">
                        </a>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>

    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @{
                var message = TempData[Criminal_Web_Station.WebConstats.Message];
                var warning = TempData[Criminal_Web_Station.WebConstats.Warning];
            }
            @if (message != null)
            {
                <div class="alert alert-success alert-message-home text-center" role="alert">
                    @message
                </div>
            }
            @if (warning != null)
            {
                <div class="alert alert-warning alert-message-home text-center" role="alert">
                    @warning
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Criminal_Web_Station - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

<script>
    $(".alert-message-home").show().delay(5000).fadeOut();
</script>